version: "3.9"

services:
  app:
    container_name: qorix-popup-docs

    build:
      context: .
      dockerfile: Dockerfile

    image: qorix-popup-docs

    restart: unless-stopped

    ports:
      - "4500:80"

    networks:
      - qorix-popup-docs-network

networks:
  qorix-popup-docs-network:
    driver: bridge